spring:
  datasource:
    url: jdbc:mysql://localhost:3306/wanted_pre_onboarding?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true